package ec.gob.dinardap.notarialregistral.constante;

public enum ParametroEnum {

	SERVIDOR_SFTP, PUERTO_SFTP, SFTP_USUARIO_NOTARIAL_REGISTRAL, SFTP_CONTRASENA_NOTARIAL_REGISTRAL,SFTP_NOTARIAL_REGISTRAL_RUTA;
}
